spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3306/study_helper
    #url: jdbc:mariadb://3.39.191.71:3306/study_helper
    driverClassName: org.mariadb.jdbc.Driver
    password: 1q2w3e4r!
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
server:
  servlet:
    session:
      tracking-modes: cookie
